name: Claims
version: '${project.version}'
main: me.stephenminer.claims.Claims
api-version: 1.19
load: POSTWORLD
commands:
  giveWand:
  claimShovel:
  claims:
  claimBlocks:
  claimsReload:
  forceDelete: